# Generated by Django 2.2.3 on 2019-07-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_file_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='document',
        ),
    ]
