# Generated by Django 2.2.3 on 2019-07-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190718_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='document',
        ),
    ]
